### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by coke11** [uuffda/uuffda.github.io#1]
The domain name is too long. We need to rename it to uuffda.tk or uuffda.com. Thoughts?

**Comment by bjskistad** [comment]
What's so special about .tk domains?

**Comment by coke11** [comment]
.tk domains are free. And yes I do agree

**Comment by bjskistad** [comment]
Let's start with a tk domain then.

**Comment by bjskistad** [comment]
How do I register it? :P

**Comment by coke11** [comment]
Ok. go to [dottk.tk](url)

**Comment by coke11** [comment]
I mean [dot.tk](url)

**Comment by bjskistad** [comment]
k.

**Comment by bjskistad** [comment]
nvm can you register it?

**Comment by bjskistad** [comment]
I gtg

**Comment by coke11** [comment]
sure

**Comment by bjskistad** [comment]
Can I have creds? And why am I getting a 502?

**Comment by coke11** [comment]
Sorry I have not done it yet XD.

**Comment by bjskistad** [comment]
XD

**Comment by coke11** [comment]
u want to do it now?

**Comment by bjskistad** [comment]
Sure. (How do I? I'm a dweeb about IPs, domains, hosting, nginx, DNS, etc.)

**Comment by coke11** [comment]
got to dot.tk snd follow the instructions

**Comment by bjskistad** [comment]
ok

**Comment by bjskistad** [comment]
Where should I look?

**Comment by bjskistad** [comment]
Ok, nvm I found a free hoster.

**Comment by coke11** [comment]
ok :). Make sure it is really free though. You can also host on blog spot

**Comment by bjskistad** [comment]
kk
